version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - ADMIN_PASSWORD=password # Use a secure password
      - DB_PASSWORD=password # Match your postgres password
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run dev