general:
  maxRecords: 2000
  ignoreNonPlate: false
mqtt:
  broker: ''
  topic: alpr/plates
database:
  host: db:5432
  name: postgres
  user: postgres
  password: password
notifications:
  pushover:
    enabled: false
    app_token: ''
    user_key: ''
    priority: 1
    sound: pushover
    title: ALPR Alert
